name: a_cameras_example
description: Demonstrates how to use the cameras plugin.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  a_cameras:
    path: ../


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
