name: a_cameras
description: A Flutter plugin for accessing camera functionalities across various platforms with a unified API. Currently supports web only.
version: 0.1.0
homepage: https://github.com/Okladnoj/cameras
repository: https://github.com/Okladnoj/cameras


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.3.0
  universal_html: ^2.2.4
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  freezed: ^2.4.2
  json_serializable: ^6.7.1


flutter:
  plugin:
    platforms:
      # android:
      #   package: com.okjl.a_cameras
      #   pluginClass: CamerasPlugin
      # ios:
      #   pluginClass: CamerasPlugin
      # linux:
      #   pluginClass: CamerasPlugin
      # macos:
      #   pluginClass: CamerasPlugin
      # windows:
      #   pluginClass: CamerasPluginCApi
      web:
        pluginClass: CamerasWeb
        fileName: src/web/cameras_web.dart

keywords:
  - camera
  - photo
  - video
  - flutter

license: MIT
